### ISSUE TITLE
Wrapping `<div class="toc">` does not work

### ISSUE THREAD

**Issue by stevenocchipinti** [signalwerk/gatsby-remark-table-of-contents#5] opened 2020-06-01 07:42 UTC
It looks like this plugin [attempts to put a `<div class="toc">` before the TOC and a `</div>` after the TOC](https://github.com/signalwerk/gatsby-remark-table-of-contents/blob/master/index.js#L68), however this results in erroneous HTML for me:

<img width="231" alt="Screen Shot 2020-06-01 at 3 02 41 pm" src="https://user-images.githubusercontent.com/790066/83386506-8977c480-a42e-11ea-8dbc-2940ced1a8bc.png">

It looks like the opening tag is being automatically closed and the closing tag is `undefined`.
Despite this erroneous HTML, the output still looks ok in the browser however it does give this error in the console:

<img width="692" alt="Screen Shot 2020-06-01 at 5 39 45 pm" src="https://user-images.githubusercontent.com/790066/83386802-fb500e00-a42e-11ea-9632-3301826b5c65.png">

**Comment by arnaud-deprez** [comment] 2020-08-13 09:08
Found someone who has similar issue and he solves it like this: https://joshuatz.com/posts/2020/gatsby-wrapping-markdown-in-html-divs-with-custom-classes/.
Not sure I will have time to propose a fix soon, so...

**Comment by signalwerk** [comment] 2020-08-21 12:21
@arnaud-deprez @stevenocchipinti if one of you found a solution for it I would highly appreciate a pull-request.

**Comment by ianobermiller** [comment] 2020-09-08 04:46
One solution would be to just not add the closing tag and if you want to stye with CSS, use the sibling selector:

```css
.toc ~ ul {
  margin: 1em 0;
  /* ... */
}
```

**Comment by arnaud-deprez** [comment] 2020-09-08 08:49
That is indeed the workaround I'm currently using @ianobermiller :-)

**Comment by signalwerk** [comment] 2020-09-08 10:56
😂 we all have the same idea...

```css

.toc + ul {

}
```

**Comment by ianobermiller** [comment] 2020-09-08 14:02
@signalwerk good call, I should use plus and not tilde.

**Comment by gerardosabetta** [comment] 2020-11-03 17:44
I have the same console error :( , any fixes for that?

**Comment by zeropaper** [comment] 2020-12-04 17:11
It should not need such a workaround in the first place. :/ 

 @stevenocchipinti are you also use MDX?

I do.

and when I add a bit of "HTML" code in my ".mdx" file, for instance:

```markdown
# heading

<div class="html-test">test</div>

## other heading
```

The AST will consider the `<div class="html-test">test</div>` bit as "jsx" as follow...

```
// ...
    },
    {
      type: 'jsx',
      value: '<div class="html-test">test</div>',
      position: [Position]
    },
    {
// ...
```

And it feels that the following lines:
https://github.com/signalwerk/gatsby-remark-table-of-contents/blob/379551c3de958c93d9e669ba9ee4205d649b7bad/src/index.js#L68-L82
 of `gatsby-remark-table-of-contents` source code... 
may need to be adapted...

**Update:** I can't reproduce the problem using the "normal" `gatsby-transformer-remark`, it's almost certainly a problem that only occurs when using MDX.

I just started digging... made a fork and if I can fix that "properly", will make a PR...

**Comment by zeropaper** [comment] 2020-12-09 11:22
Grüetzi @signalwerk :)

any chance to get [my PR](https://github.com/signalwerk/gatsby-remark-table-of-contents/pull/13) reviewed / merged in the coming days?
That would be immensely appreciated!

**Comment by signalwerk** [comment] 2020-12-09 14:09
@zeropaper Thank you for your contribution. I didn't time since last weekend to review and document your PR. I will try to do that this week. Sorry for the delay.

**Comment by signalwerk** [comment] 2020-12-13 22:00
@stevenocchipinti @arnaud-deprez @ianobermiller I just merged @zeropaper [PR](https://github.com/signalwerk/gatsby-remark-table-of-contents/pull/13) and bumped the npm to version 1.0.0. Please make sure if you update to fix zur css definitions. The DOM is now correct and the `.toc` wraps the whole Table of content

new:
```css
.toc .ul {
 …
}
```

Thank you @zeropaper for your highly appreciated work!

**Closed as completed** 2020-12-13 22:00 UTC

**Comment by stevenocchipinti** [comment] 2020-12-13 23:43
Thank you all :D
